# Generated by Django 2.2.1 on 2019-10-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190912_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='organization',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='job_possition',
            new_name='job_position',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='job_possition',
            new_name='job_position',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='recruiter',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='level',
        ),
        migrations.AddField(
            model_name='quiz',
            name='job_position',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='app.JobPosting'),
        ),
        migrations.DeleteModel(
            name='ApplicationTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
