# Generated by Django 2.2.1 on 2019-10-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_recruiter_is_superadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='quiz',
        ),
    ]
