# Generated by Django 2.2.1 on 2019-10-17 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191016_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='description',
            field=models.CharField(default='Domyślny opis', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.JobPosting'),
        ),
    ]
