# Generated by Django 2.2.1 on 2019-10-17 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191017_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job_position',
        ),
        migrations.AddField(
            model_name='application',
            name='quiz',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='app.Quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='ApplicationQuiz',
        ),
    ]
