# Generated by Django 2.2.1 on 2019-10-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191017_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attachment',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='Rozpatrywana', max_length=50),
        ),
    ]
