# Generated by Django 2.2.1 on 2019-10-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191026_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
