# Generated by Django 2.2.1 on 2019-10-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_application_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
