# Generated by Django 2.2.1 on 2019-10-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191027_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_boolean',
            new_name='is_true',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='description',
        ),
    ]
