# Generated by Django 2.2.1 on 2019-10-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191028_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='full_score',
            field=models.IntegerField(default=0),
        ),
    ]
